:rotating_light: Fix: linter configuration.

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -1,12 +1,38 @@
 #!/bin/bash
 
-if which swiftlint >/dev/null; then
-  swiftlint --fix
+export PATH=/usr/local/bin:$PATH
+
+LINT=$(which swiftlint)
+
+if [[ -e "${LINT}" ]]; then
+	echo "SwiftLint Start..."
+	echo $(pwd)
 else
-  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
+	echo "SwiftLint does not exist, download from https://github.com/realm/SwiftLint"
+	exit 1
 fi
 
-git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
-  swiftformat "${line}";
-  git add "$line";
-done
+RESULT=$($LINT lint --quiet --config .swiftlint.yml)
+
+if [ "$RESULT" == '' ]; then
+	printf "SwiftLint Finished.\n"
+else
+	echo ""
+	printf "SwiftLint Failed. Please check below:\n"
+
+	while read -r line; do
+		FILEPATH=$(echo $line | cut -d : -f 1)
+		L=$(echo $line | cut -d : -f 2)
+		C=$(echo $line | cut -d : -f 3)
+		TYPE=$(echo $line | cut -d : -f 4 | cut -c 2-)
+		MESSAGE=$(echo $line | cut -d : -f 5 | cut -c 2-)
+		DESCRIPTION=$(echo $line | cut -d : -f 6 | cut -c 2-)
+		printf "\n $TYPE\n"
+		printf "    $FILEPATH:$L:$C\n"
+		printf "    $MESSAGE - $DESCRIPTION\n"
+	done <<< "$RESULT"
+
+	printf "\nCOMMIT ABORTED. Please fix them before commiting.\n"
+
+	exit 1
+fi
